/**
 * take/prints.js (B6) — generative flash photographs, deterministic per
 * seed (constitution §6/§8.2). getPrintRoster(): static ~14-entry BLOTTER
 * gallery; drop:photo brings its own seed to paintPrint().
 * GOTCHA: no grain/tears here (sacred photo, §8.2). Hex mirrors tokens.css.
 * Streaks use vapor/ember only — never red/blue (§2, §8.5).
 */

import { makeRng, rangeInt, pick } from '../core/rng.js';
import { BLOTTER } from '../data/strings.js';

const INK = { deep: '#0E0A06', vapor: '#EAD9C0', hot: '#FFC46B', sodium: '#FF9F1C', ember: '#B36A0A', flash: '#FFF8EC' };
const TAU = Math.PI * 2;

/** `DATE · VENUE · "his words"` — his caption verbatim, or just DATE · VENUE
 *  when a post had none. Nothing is invented and put in his mouth. */
export function formatDropCaption(d) {
  const head = [d.date ? d.date.toUpperCase() : '', d.venue || ''].filter(Boolean).join(' · ');
  const words = (d.caption || '').trim();
  return words ? `${head} · “${words}”` : head;
}

/**
 * Load the real photo-drop manifest (assets/drops/drops.json) — HIS actual
 * Instagram photos + captions. Regenerated by scripts/sync-instagram.py (the
 * auto-populate pipeline). Returns a newest-first roster [{seed, caption, img}]
 * or null when unavailable/empty, so the gallery falls back to generative prints.
 * @returns {Promise<Array<{seed:string,caption:string,img:string}>|null>}
 */
export async function loadDrops() {
  try {
    const res = await fetch('assets/drops/drops.json', { cache: 'no-store' });
    if (!res.ok) return null;
    const data = await res.json();
    const drops = Array.isArray(data.drops) ? data.drops : [];
    if (!drops.length) return null;
    return drops
      .filter((d) => d && d.file)
      .map((d) => ({ seed: `print:real:${d.id}`, caption: formatDropCaption(d), img: d.file }));
  } catch (_) { return null; }
}

/** The generative fallback roster (deterministic BLOTTER prints) — used only
 *  when the real manifest is missing/empty. */
export function getGenerativeRoster() {
  const COUNT = 14, N = BLOTTER.length, seen = new Set(), out = [];
  for (let i = 0; i < COUNT; i++) {
    const idx = Math.round((i * (N - 1)) / (COUNT - 1));
    if (seen.has(idx)) continue;
    seen.add(idx);
    out.push({ seed: `print:blotter:${idx}`, caption: formatCaption(BLOTTER[idx]) });
  }
  return out;
}

/** `${time} · ${street} · ${lens} · ${line}` per strings.js's BlotterEntry doc. */
export function formatCaption(e) { return `${e.time} · ${e.street} · ${e.lens} · ${e.line}`; }

/** Paint one generative flash photograph. Deterministic on seedStr (Determinism Law §8.1). */
export function paintPrint(ctx, w, h, seedStr) {
  const rng = makeRng(seedStr), rnd = (a, b) => a + rng() * (b - a);
  ctx.clearRect(0, 0, w, h);
  ctx.fillStyle = INK.deep;
  ctx.fillRect(0, 0, w, h);

  const fx = w * rnd(0.18, 0.82), fy = h * rnd(0.08, 0.5), rad = Math.max(w, h) * rnd(0.55, 0.85);
  const flare = ctx.createRadialGradient(fx, fy, 0, fx, fy, rad);
  flare.addColorStop(0, INK.flash); flare.addColorStop(0.07, INK.hot); flare.addColorStop(0.22, INK.sodium);
  flare.addColorStop(0.42, INK.ember + '55'); flare.addColorStop(1, INK.deep + '00');
  ctx.globalCompositeOperation = 'lighter';
  ctx.fillStyle = flare;
  ctx.fillRect(0, 0, w, h);
  ctx.globalCompositeOperation = 'source-over';

  const massCount = rangeInt(`${seedStr}:masses`, 2, 4);
  const kinds = ['figure', 'figure', 'figure', 'bike', 'structure'];
  const masses = [];
  for (let i = 0; i < massCount; i++) {
    const cx = w * rnd(0.1, 0.9), cy = h * rnd(0.45, 0.92);
    masses.push({ cx, cy });
    drawSilhouette(ctx, pick(`${seedStr}:kind:${i}`, kinds), cx, cy, w, h, `${seedStr}:mass:${i}`);
  }

  const streaked = masses[rangeInt(`${seedStr}:streakpick`, 0, masses.length - 1)];
  if (streaked) drawStreaks(ctx, streaked, w, h, `${seedStr}:streak`);
}

/** figure mid-dance, bike, or blocky street furniture (doorframe/dumpster). */
function drawSilhouette(ctx, kind, cx, cy, w, h, seedStr) {
  const rng = makeRng(seedStr), rnd = (a, b) => a + rng() * (b - a), sc = rnd(0.75, 1.2) * Math.min(w, h) * 0.01;
  ctx.save();
  ctx.translate(cx, cy);
  ctx.rotate(rnd(-0.08, 0.08));
  ctx.fillStyle = 'rgba(5,3,1,0.94)';

  if (kind === 'figure') {
    const spread = rnd(10, 26) * sc;
    ctx.beginPath(); ctx.moveTo(-spread, 0); ctx.lineTo(spread, 0); ctx.lineTo(6 * sc, 46 * sc); ctx.lineTo(-6 * sc, 46 * sc); ctx.closePath(); ctx.fill();
    ctx.beginPath(); ctx.ellipse(rnd(-5, 5) * sc, -18 * sc, 13 * sc, 17 * sc, rnd(-0.2, 0.2), 0, TAU); ctx.fill(); // torso
    ctx.beginPath(); ctx.arc(0, -34 * sc, 7 * sc, 0, TAU); ctx.fill();
  } else if (kind === 'bike') {
    const r = 14 * sc;
    for (const wx of [-20 * sc, 20 * sc]) { ctx.beginPath(); ctx.arc(wx, 0, r, 0, TAU); ctx.fill(); }
    ctx.beginPath(); ctx.moveTo(-20 * sc, 0); ctx.lineTo(4 * sc, -20 * sc); ctx.lineTo(20 * sc, 0); ctx.closePath(); ctx.fill();
  } else { // structure
    const bw = rnd(0.14, 0.26) * w, bh = rnd(0.12, 0.5) * h;
    ctx.fillRect(-bw / 2, -bh, bw, bh);
    if (rng() > 0.5) { ctx.fillStyle = INK.deep; ctx.fillRect(-bw * 0.3, -bh * 0.85, bw * 0.6, bh * 0.7); }
  }
  ctx.restore();
}

/** motion-blur + chromatic-style offset — vapor/ember, never red/blue (§2, §8.5) */
function drawStreaks(ctx, mass, w, h, seedStr) {
  const rng = makeRng(seedStr), rnd = (a, b) => a + rng() * (b - a);
  const angle = rnd(-0.5, 0.5), count = rangeInt(`${seedStr}:n`, 3, 5), baseLen = Math.min(w, h) * rnd(0.12, 0.28);
  const dx = Math.cos(angle), dy = Math.sin(angle), off = rnd(1, 2) * (rng() > 0.5 ? 1 : -1);
  const passes = [[INK.vapor, 0, 0, 0.5], [INK.ember, off, off, 0.35]];
  ctx.lineWidth = Math.max(1, Math.min(w, h) * 0.006);
  for (const [tint, ox, oy, alpha] of passes) {
    ctx.strokeStyle = tint;
    ctx.globalAlpha = alpha;
    for (let i = 0; i < count; i++) {
      const len = baseLen * rnd(0.5, 1), sx = mass.cx + ox + rnd(-14, 14), sy = mass.cy + oy + rnd(-30, 4);
      ctx.beginPath(); ctx.moveTo(sx, sy); ctx.lineTo(sx - dx * len, sy - dy * len); ctx.stroke();
    }
  }
  ctx.globalAlpha = 1;
}
